Repository MAVRICK-1/e-commerce_website, pull requests merged in 2024-05, with the labels that each got.

#34 feat: redux provider
  package-lock.json
  package.json
  src/Redux/store.js
  src/index.js
Labels: GSSoC'24, level 2, gssoc

#62 Feature Request: Add Favicons to Website
  public/favicon.ico
Labels: GSSoC'24, level1, gssoc

#65 Profile Image Not Displaying Upon Sign-in Fixed
  src/components/header/header.js
  src/pages/SignIn/index.js
  src/pages/SignIn/style.css
Labels: GSSoC'24, level3, gssoc

#76 anchor tag styling fixed and link tags added into other items
  src/components/header/header.js
  src/components/header/nav/nav.js
Labels: GSSoC'24, level2, gssoc

#78 updated and done necessary changes for About Us page
  src/pages/About/index.js
  src/pages/About/style.css
Labels: GSSoC'24, level3, gssoc

#84 Bug in About us page Fixed
  src/pages/About/index.js
  src/pages/About/style.css
Labels: GSSoC'24, level3, gssoc

#99 Create greetings.yaml #82
  .github/workflows/greetings.yaml
Labels: GSSoC'24, level2, gssoc

#112 Updated README.md
  README.md
Labels: GSSoC'24, level3, gssoc

#134 Forgot password
  src/App.js
  src/pages/ResetPassword/index.js
  src/pages/ResetPassword/style.css
  src/pages/SignIn/index.js
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#137 Main page groceries, electronics, fashion buttons Not Working Fixed
  src/App.js
  src/components/header/header.js
  src/components/header/nav/nav.js
  src/pages/Details/index.js
  src/pages/wishList/index.js
Labels: GSSoC'24, level2, gssoc

#143 Fix issue 72
  src/App.js
  src/components/footer/footer.js
Labels: GSSoC'24, level1, gssoc

#128 Feat/my account
  .idea/.gitignore
  .idea/e-commerce_website.iml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/App.js
  src/Model/useModel.js
  src/assets/images/pfp.jpg
  src/components/AccountDetails/Account.css
  src/components/AccountDetails/Account.js
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/header/nav/nav.js
  src/pages/About/about.css
  src/pages/About/index.js
  src/pages/ResetPassword/index.js
  src/pages/ResetPassword/style.css
  src/pages/SignIn/index.js
  src/pages/wishList/index.js
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#148 [Feat]: GoToTop button added
  package-lock.json
  package.json
  src/App.js
  src/components/GoToTop/GoToTop.css
  src/components/GoToTop/GoToTop.js
  yarn.lock
Labels: GSSoC'24, level2, gssoc

#153 Issue/149: Image Optimization for reducing loading time
  src/App.js
  src/assets/images/app-store.jpg
  src/assets/images/app-store.webp
  src/assets/images/banner1.jpg
  src/assets/images/banner1.webp
  src/assets/images/banner2.jpg
  src/assets/images/banner2.webp
  src/assets/images/banner3.jpg
  src/assets/images/banner3.webp
  src/assets/images/banner4.jpg
  src/assets/images/banner4.webp
  src/assets/images/bg.png
  src/assets/images/bg.webp
  src/assets/images/google-play.jpg
  src/assets/images/google-play.webp
  src/assets/images/google.png
  src/assets/images/google.webp
  src/assets/images/newsletter.png
  src/assets/images/newsletter.webp
  src/assets/images/page-404.png
  src/assets/images/page-404.webp
  src/assets/images/payment-method.png
  src/assets/images/payment-method.webp
  src/assets/images/pfp.jpg
  src/assets/images/pfp.webp
  src/assets/images/search.png
  src/assets/images/search.webp
  src/assets/images/slider-1.png
  src/assets/images/slider-1.webp
  src/assets/images/slider-2.png
  src/assets/images/slider-2.webp
  src/assets/images/thumbnail-1.jpg
  src/assets/images/thumbnail-1.webp
  src/assets/images/thumbnail-2.jpg
  src/assets/images/thumbnail-2.webp
  src/assets/images/thumbnail-3.jpg
  src/assets/images/thumbnail-3.webp
  src/components/AccountDetails/Account.js
  src/components/GoToTop/GoToTop.css
  src/components/GoToTop/GoToTop.js
  src/components/Sidebar/index.js
  src/components/banners/index.js
  src/components/footer/footer.js
  src/pages/Home/TopProducts/index.js
  src/pages/Home/index.js
  src/pages/Home/slider/index.js
  src/pages/Home/style.css
  src/pages/NotFound/index.js
  src/pages/ResetPassword/index.js
  src/pages/SignIn/index.js
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#160 Compare page and it's functionality Fixed
  src/App.js
  src/components/header/header.js
  src/pages/Compare/index.js
  src/pages/Compare/style.css
  src/pages/Details/index.js
Labels: GSSoC'24, level3, gssoc

#173 Re design card
  .gitignore
  src/App.js
  src/components/header/header.js
  src/components/search/SearchResults.jsx
  src/useFetchData.js
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#177 updated about
  src/pages/About/about.css
Labels: GSSoC'24, level2, gssoc

#176 Shop dropdown text enhancement
  src/components/header/nav/nav.css
  src/components/header/nav/nav.js
  yarn.lock
Labels: level1, gssoc

#174 add the hyperlink in my wish-list
  package-lock.json
  src/components/header/header.js
Labels: level1, gssoc

#179 Location. (no need for country names, Indian cities name should be there) Fixed
  src/components/header/cities.js
  src/components/header/header.js
Labels: GSSoC'24, level2, gssoc

#180 Added a Chatbot
  package-lock.json
  public/index.html
  src/App.js
  yarn.lock
Labels: GSSoC'24, level2, gssoc

#190 GoToTop Issue Fixed
  src/App.js
  src/components/GoToTop/GoToTop.css
  src/components/GoToTop/GoToTop.js
Labels: GSSoC'24, level1, gssoc

#188 Added button for back to SignIn #154
  package-lock.json
  src/App.js
  src/pages/ResetPassword/index.js
  src/pages/SignIn/index.js
  yarn.lock
Labels: GSSoC'24, level1, gssoc

#193 Add Twitter logo button to footer
  package-lock.json
  package.json
  src/components/footer/footer.css
  src/components/footer/footer.js
  yarn.lock
Labels: GSSoC'24, level2, gssoc

#201 [Bug]Removed repetitive content
  src/components/footer/footer.js
Labels: GSSoC'24, gssoc

#205 ScrollToTop UI improved
  src/components/GoToTop/GoToTop.css
  src/components/GoToTop/GoToTop.js
Labels: GSSoC'24, level1, gssoc

#209 feat #199 : implement the shipping Addresses feature
  package.json
  src/App.js
  src/components/AccountDetails/Account.js
  src/components/ShippingAddress/AddressData.jsx
  src/components/ShippingAddress/Shipping.css
  src/components/ShippingAddress/ShippingForm.jsx
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/header/nav/nav.css
  src/components/header/nav/nav.js
  src/components/search/SearchResults.jsx
  src/pages/About/about.css
  src/pages/About/index.js
  src/pages/Compare/index.js
  src/pages/Compare/style.css
  src/pages/Details/index.js
  src/pages/Home/style.css
  src/pages/ResetPassword/index.js
  src/pages/ResetPassword/style.css
  src/pages/SignIn/index.js
  src/pages/wishList/index.js
  src/useFetchData.js
Labels: GSSoC'24, level3, gssoc

#219 Update react-router-dom to version 6 and refactor routing logic
  src/App.js
  src/components/header/nav/nav.js
Labels: GSSoC'24, level2, gssoc

#222 Hover effect added
  src/App.css
  src/components/header/header.css
Labels: GSSoC'24, level1, gssoc

#224 [NEW FEATURE] Added Modal Component To Display Deal of the Day
  package-lock.json
  package.json
  src/assets/images/icon-cart.png
  src/assets/images/icon-close.svg
  src/assets/images/icons-arrow.png
  src/assets/images/strawberryBottle.webp
  src/components/DealofDay/DealofDay.css
  src/components/DealofDay/DealofDay.js
  src/pages/Home/index.js
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#239 UI of Deals of the day Modal Improved
  src/components/DealofDay/DealofDay.css
  src/components/DealofDay/DealofDay.js
Labels: GSSoC'24, level2, gssoc

#246 Redirect to Google Map Fixed
  src/components/footer/footer.js
Labels: level1, gssoc

#248 OTP verification system for SignIn functionality-#203
  package-lock.json
  package.json
  src/firebase.js
  src/pages/SignUp/index.js
  yarn.lock
Labels: level2, gssoc

#255 Enhanced the wishlist page and added 'Move to cart' button
  src/pages/wishList/index.js
  src/pages/wishList/style.css
  yarn.lock
Labels: level3, gssoc

#253 About Section Enhanced
  src/assets/images/bg2.jpg
  src/pages/About/about.css
  src/pages/About/index.js
Labels: level2, gssoc

#251 Nav hover and browse all category position Fixed
  src/components/header/nav/nav.css
  src/components/header/nav/nav.js
Labels: level1, gssoc

#202 adding_mailto_tel_functionallity
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: GSSoC'24, level1, gssoc
