Repository MAVRICK-1/e-commerce_website, pull requests merged in 2024-06, with the labels that each got.

#281 Styled added to Scrollbar
  src/index.css
  yarn.lock
Labels: GSSoC'24, level1, gssoc

#278 feat #260 : Order tracking Functionality
  package-lock.json
  src/App.js
  src/components/OrderTracking/OrderTable.js
  src/components/OrderTracking/StepCounter.js
  src/components/header/header.js
  src/pages/OrderTracking/TrackOrderDetails.js
  src/pages/OrderTracking/index.js
  src/pages/OrderTracking/style.css
  yarn.lock
Labels: GSSoC'24, level3, gssoc

#295 Updated About Page
  src/assets/images/delivery.png
  src/assets/images/deliveryhover.png
  src/assets/images/payment.png
  src/assets/images/paymenthover.png
  src/assets/images/product.png
  src/assets/images/producthover.png
  src/assets/images/ux.png
  src/assets/images/uxhover.png
  src/pages/About/About.jsx
  src/pages/About/about.css
  src/pages/About/index.js
Labels: GSSoC'24, level2, gssoc

#316 Create Contact Us page #299
  package-lock.json
  package.json
  src/App.js
  src/pages/Contactus/Contactus.jsx
  src/pages/Contactus/contactus.css
Labels: GSSoC'24, level3, gssoc

#314 [Feature Request]: Want to add skeleton #288added skeleton
  src/App.css
  src/components/Skeletons/HomeSliderSkeleton.js
  src/components/Skeletons/Product_Skeleton.jsx
  src/components/Skeletons/TopProductsSkeleton.js
  src/components/banners/index.js
  src/components/map/map.css
  src/components/product/index.js
  src/pages/Home/TopProducts/index.js
  src/pages/Home/slider/index.js
Labels: GSSoC'24, level3, gssoc

#312 overlapping of leaflet control button
  public/index.html
Labels: GSSoC'24, level1, gssoc

#304 hover effect added
  src/App.css
  src/responsive.css
Labels: GSSoC'24, level1, gssoc

#335 faq section added wrt issue #283
  package-lock.json
  package.json
  src/App.js
  src/components/faq/FAQ.css
  src/components/faq/FAQ.js
Labels: GSSoC'24, level2, gssoc

#347 add blog page (fixes #275)
  src/App.js
  src/pages/blog/blog.css
  src/pages/blog/blog.jsx
  src/pages/blog/data.jsx
Labels: GSSoC'24, level3, gssoc

#342 [Feature Request]: Want to Improve Ui of Add Product Page #334
  src/pages/AddProd/index.js
Labels: GSSoC'24, level2, gssoc

#351 the size of all the boxes made same
  src/components/footer/footer.css
Labels: GSSoC'24, level1, gssoc

#352 Improved the UI of the Get In Touch Section
  src/pages/Contactus/Contactus.jsx
  src/pages/Contactus/contactus.css
Labels: GSSoC'24, level2, gssoc

#360 Chat button and the bottom to top button mobile view aligned fixed
  src/components/GoToTop/GoToTop.css
Labels: good first issue, GSSoC'24, level1, gssoc

#200 Changes favicon
  public/favicon.ico
Labels: GSSoC'24, level1, gssoc

#361 Customer care number is now visible
  src/App.css
Labels: GSSoC'24, gssoc

#339 updated gototop
  src/components/GoToTop/GoToTop.css
Labels: GSSoC'24, level1, gssoc

#365 [Bug Fix] : Fixes #340 - Support Center Contact number not visible (helpline-num-fix)
  src/components/header/nav/nav.css
  src/components/header/nav/nav.js
Labels: GSSoC'24, gssoc

#378 Linked the about us in the footer #364
  src/components/footer/footer.js
  src/pages/About/About.jsx
Labels: GSSoC'24, level1, gssoc

#393 Added A New "Scroll to Top Button" Functionality
  src/components/GoToTop/GoToTop.css
  src/components/GoToTop/GoToTop.js
  src/components/footer/footer.js
Labels: GSSoC'24, level1, gssoc

#392 Added "Navigation Links" to the "FAQ Section" in Footer
  src/App.js
  src/components/faq/FAQ.js
  src/components/footer/footer.js
Labels: GSSoC'24, level1, gssoc

#379 Improved SEO
  src/pages/Home/TopProducts/index.js
  src/pages/Home/index.js
  src/pages/Home/slider/index.js
Labels: GSSoC'24, level2, gssoc

#372 text-align in About page
  npm.cmd
  npx.cmd
  src/pages/About/about.css
Labels: bug, GSSoC'24, level1, gssoc

#414 [Feature Request]: Want to Improve Card Design #40
  src/App.css
  src/components/product/index.js
  src/components/product/style.css
  src/pages/Home/style.css
  src/pages/blog/blog.css
Labels: GSSoC'24, level2, gssoc

#366 Solved the issue of page rendering at bottom
  src/pages/PrivacyPolicy/index.js
  src/pages/TermsAndConditions/index.js
Labels: GSSoC'24, level1, gssoc

#432 hover effects added
  src/components/header/nav/nav.css
Labels: GSSoC'24, level1, gssoc

#434 Profile
  src/components/AccountDetails/Account.css
  src/components/AccountDetails/Account.js
  src/components/header/header.js
Labels: GSSoC'24, level3, gssoc
